fix: exclude observations if too few samples in bin
Aarhus-Psychiatry-Research/psycop-model-training pull request #408
Opened 2023-03-06 21:09 UTC by sarakolding

- [x] I have battle-tested on Overtaci (RMAPPS1279)
- [x] At least one of the commits is prefixed with either "fix:" or "feat:"

2023-03-06 21:27 UTC, sarakolding commented on src/psycop_model_training/utils/utils.py
> +    return df[df.groupby("bin")["series"].transform("size") >= min_n_in_bin]
saw that the test failed because this is supposed to a series, rather than a dataframe. that's an easy fix, except we subset the data here, and it won't fit later. i'll put a comment where

2023-03-06 21:35 UTC, sarakolding commented on src/psycop_model_training/model_eval/base_artifacts/plots/utils.py
>          df[f"{input_name}_binned"] = bin_continuous_data(df[input_name], bins=bins)
here: if some bins have less than min_n_in_bins, I think this series will be the wrong size for data frame. maybe move filtering here instead? might just be me, brain has gone a bit mushy

2023-03-07 13:35 UTC, MartinBernstorff requested changes
Thanks for taking a look at this! Have suggested some changes.

2023-03-07 13:35 UTC, MartinBernstorff commented on src/psycop_model_training/utils/utils.py
> +    return df.bin[df.groupby("bin")["series"].transform("size") >= min_n_in_bin]
```suggestion
    bins_with_sufficient_n = df.groupby("bin")["series"].transform("size") >= min_n_in_bin
    return df.bin[bins_with_sufficient_n]
```

Splitting this out into a variable makes it **much** easier to read :-)

2023-03-07 13:35 UTC, MartinBernstorff commented on src/psycop_model_training/model_eval/base_artifacts/plots/utils.py
>          df[f"{input_name}_binned"] = bin_continuous_data(df[input_name], bins=bins)
Agreed, might very well be a problem. Instead of dropping the bins, we could just replace their value with na - that should solve it.

2023-03-07 17:24 UTC, MartinBernstorff commented
Hey Sara! Just wanna say that this'll be super helpful - I'm trying to run some plots now where this defect is causing them to be empty.

2023-03-07 20:38 UTC, sarakolding commented on src/psycop_model_training/utils/utils.py
> +    return df["bin"].mask(bins_with_insufficient_n)
masked bins with too few samples with NaN

2023-03-08 09:24 UTC, MartinBernstorff commented
Det ser super ud! Jeg skriver lige en test eller to, og så er den vist klar til merge.

2023-03-08 09:49 UTC, merged