feat: cache preprocessed datasets for higher performance
Aarhus-Psychiatry-Research/psycop-model-training pull request #429
Opened 2023-03-17 12:13 UTC by MartinBernstorff

Joblib's cache uses the inputs for cache invalidation - would especially like comments on whether this seems reasonable. Don't want invalidation errors again :-(

2023-03-17 12:20 UTC, HLasse approved these changes
See below

2023-03-17 12:30 UTC, HLasse requested changes

2023-03-17 12:30 UTC, HLasse commented on src/psycop_model_training/data_loader/utils.py
> +memory = Memory(location=memory_path, verbose=0)
This is gonna break if you install the module locally. Perhaps move the `memory_path` to the config and run the deletion before `load_and_filter_split_from_cfg` is called?

2023-03-17 12:34 UTC, MartinBernstorff commented on src/psycop_model_training/data_loader/utils.py
> +memory = Memory(location=memory_path, verbose=0)
You're right - and the tests are failing as well. Will look at it, thanks!

2023-03-21 13:09 UTC, MartinBernstorff commented
I've thought about using the current git commit as a hash, but that also seems overly strict. Not quite sure how to do this effectively, so might end up just not doing it at all :-(

2023-03-23 13:15 UTC, closed without merging