Offset negative values
Aarhus-Psychiatry-Research/psycop-model-training pull request #472
Opened 2023-04-04 09:29 UTC by signekb

- [X] I have battle-tested on Overtaci (RMAPPS1279)
- [X] At least one of the commits is prefixed with either "fix:" or "feat:"

## Notes for reviewers
Adding the option to offset column values by most negative value, so all values are non-negative.

2023-04-04 13:00 UTC, MartinBernstorff commented
> It fails bc I have added "self.pre_split_cfg.offset_negative_values" which is not in the cfg. I remember that you've said that we should try to avoid adding variables to cfgs (bc everyone will need to add it to their projects), but unsure how else it can be implemented? Since we are now running with f_classif instead of chi2, this is not a big issue for us anymore, but might be nice to have as an option 👍

Yeah, totally!

When running tests, we use the config objects from the tests directory. To fix the error, you just need to add the key to those files :-)

2023-04-04 13:06 UTC, MartinBernstorff requested changes

2023-04-04 13:06 UTC, MartinBernstorff commented on src/psycop_model_training/preprocessing/pre_split/processors/value_cleaner.py
> +    def _offset_negative_values(self, dataset: pd.DataFrame) -> pd.DataFrame:
Would prefer calling this something like "offset_values_so_no_negatives", since we offset all the values, not just the negative ones :-)

2023-04-04 13:06 UTC, MartinBernstorff commented on src/psycop_model_training/preprocessing/pre_split/processors/value_cleaner.py
> +        numerical_columns_with_negative_values = [
Variable naming here is on point, strong progress from you guys! 🥳

2023-04-04 13:06 UTC, MartinBernstorff commented on src/psycop_model_training/preprocessing/pre_split/processors/value_cleaner.py
> +        col_min_values = [df_to_replace[c].min() for c in df_to_replace]
Code based on taking two orderings and zipping them together is typically brittle - if we add anything in the future which changes the ordering, this code will zip them together without complaining, but the results will be completely wrong.

I'd propose two solutions:
1. (Mandatory): Write a test for this method. Since it doesn't use the self argument, you can convert it to a @staticmethod and just straight up apply it.
2. Convert to using a dict which maps from column name to minimum value
```suggestion
        col_min_values = {c: df_to_replace[c].min() for c in df_to_replace]}
```
And then adapt the code that comes after.

2023-04-07 11:55 UTC, signekb commented on src/psycop_model_training/preprocessing/pre_split/processors/value_cleaner.py
> +    def _offset_negative_values(self, dataset: pd.DataFrame) -> pd.DataFrame:
Ah, agreed!

2023-04-11 10:56 UTC, signekb commented on src/psycop_model_training/preprocessing/pre_split/processors/value_cleaner.py
> +        col_min_values = [df_to_replace[c].min() for c in df_to_replace]
Good point. I have changed it and added tests 👍

2023-04-11 13:26 UTC, MartinBernstorff reviewed
Minor comments! Feel free to ask me what I mean and merge when implemented.

2023-04-11 13:26 UTC, MartinBernstorff commented on tests/test_preprocessing/test_value_cleaner.py
> +def test_offset_so_no_negative_values():
This is excellent! One note: All the series are monotonically increasing, so we don't test whether it gets min or just offsets from the first value. Super simple to fix - just re-order some of the values in e.g. pred_2.

In general, keep the tests as minimal as possible and highlight what each test does. I've added a comment below to highlight this.

2023-04-11 13:26 UTC, MartinBernstorff commented on tests/test_preprocessing/test_value_cleaner.py
> +            "pred_2": [-100, -50, 0, 50, 100],
These tests test the same thing - I'd re-order pred_2 to test for non monotonically increasing.

2023-04-11 13:26 UTC, MartinBernstorff commented on tests/test_preprocessing/test_value_cleaner.py
> +            "pred_3": [0, 1, 2, 3, 4],
```suggestion
            "pred_1": [-10, -5, 0, 5, 10],  # Monotonically increasing
            "pred_2": [-100, -50, 0, 50, 100],  # If the first value is not the min
            "pred_3": [0, 1, 2, 3, 4], # Should not be offset
```

2023-04-11 13:26 UTC, MartinBernstorff commented on tests/test_preprocessing/test_value_cleaner.py
> +def test_offset_so_no_negative_values_not_same_ordering():
Not sure what this test adds? :-)

2023-04-25 14:10 UTC, signekb commented on tests/test_preprocessing/test_value_cleaner.py
> +def test_offset_so_no_negative_values_not_same_ordering():
Removed 👍

2023-04-26 06:45 UTC, MartinBernstorff commented
Looks awesome, merging!

2023-04-26 06:45 UTC, MartinBernstorff approved these changes

2023-04-26 06:50 UTC, merged